import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}>
        <header className="bg-gray-900 text-white text-center py-4 text-xl font-semibold shadow">
          Ugo Manzo
        </header>

        <nav className="bg-gray-800 text-white flex justify-center gap-6 py-3">
          <Link href="/" className="hover:underline">Home</Link>
          <Link href="/about" className="hover:underline">Chi sono</Link>
          <Link href="/skills" className="hover:underline">Competenze</Link>
          <Link href="/projects" className="hover:underline">Progetti</Link>
          <Link href="/contact" className="hover:underline">Contatti</Link>
        </nav>

        <main className="min-h-screen px-4 py-8">
          {children}
        </main>

        <footer className="bg-gray-100 text-center text-sm text-gray-500 py-4 border-t mt-8">
          © {new Date().getFullYear()} Ugo Manzo – Tutti i diritti riservati.
        </footer>
      </body>
    </html>
  );
}
